# Nombre del workflow que aparecerá en la interfaz de GitHub
name: Push Branch Validator

# Evento que activa el workflow
on:
  push:
    branches-ignore:
      - main
      - master


# Jobs que se ejecutarán
jobs:
  # Nombre del job
  validate-branch:
    # Runner donde se ejecutará (Ubuntu)
    runs-on: ubuntu-latest

    # Pasos que se ejecutarán en orden
    steps:
      # Paso 1: Hacer checkout del repositorio (opcional si solo necesitamos la rama)
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Paso 2: Mostrar rama actual (para debug)
      - name: Mostrar rama actual
        run: |
          echo "=== Información de la rama ==="
          echo "Rama actual: ${{ github.ref_name }}"

      # Paso 3: Validar prefijo de nombre de rama
      - name: Validar prefijo de nombre de rama
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Validando nombre de rama: $BRANCH_NAME"

          # Comprobamos si el nombre cumple con la convención
          if echo "$BRANCH_NAME" | grep -Eq '^(feature/|bugfix/|hotfix/)'; then
            echo "✅ Nombre de rama válido."
          else
            echo "❌ ERROR: El nombre de la rama no cumple con la convención."
            echo "Debe comenzar con uno de los siguientes prefijos:"
            echo "  - feature/"
            echo "  - bugfix/"
            echo "  - hotfix/"
            exit 1
          fi
