# Nombre del workflow que aparecerá en la interfaz de GitHub
name: Push Branch Validator

# Evento que activa el workflow
on:
  push:
    # Ignorar las ramas principales para que no se ejecute en main o master
    branches-ignore: 
      - main
      - master

# Jobs que se ejecutarán
jobs:
  # Job principal: Validación de nombres de rama
  validate-branch:
    # Runner donde se ejecutará (Ubuntu)
    runs-on: ubuntu-latest

    # Pasos del job
    steps:
      # Paso 1: Hacer checkout del repositorio (buena práctica)
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Paso 2: Validar prefijo de nombre de rama
      - name: Validar prefijo de nombre de rama
        run: |
          # Guardamos el nombre de la rama en una variable
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Validando nombre de rama: $BRANCH_NAME"

          # Comprobamos si el nombre cumple con la convención
          if echo "$BRANCH_NAME" | grep -Eq '^(feature/|bugfix/|hotfix/)'; then
            echo "Nombre de rama válido."
          else
            # Si no cumple, el job falla con exit 1
            echo "ERROR: El nombre de la rama no cumple con la convención."
            echo "Debe comenzar con uno de los siguientes prefijos:"
            echo "  - feature/"
            echo "  - bugfix/"
            echo "  - hotfix/"
            exit 1
                  fi
