name: Push Branch Validator

on:
  push:
    # Se ejecuta en push, pero ignora main y master
    branches-ignore:
      - main
      - master

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar rama actual
        run: |
            echo "Rama actual: ${{ github.ref_name }}"

      - name: Validar prefijo de nombre de rama
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Validando nombre de rama: $BRANCH_NAME"

          # Comprobamos si el nombre cumple con la convención
          if echo "$BRANCH_NAME" | grep -Eq '^(feature/|bugfix/|hotfix/)'; then
            echo "✅ Nombre de rama válido."
          else
            echo "❌ ERROR: El nombre de la rama no cumple con la convención."
            echo "Debe comenzar con uno de los siguientes prefijos:"
            echo "  - feature/"
            echo "  - bugfix/"
            echo "  - hotfix/"
            exit 1
          fi
